### ISSUE TITLE
Problemas con el envío de ubicación

### ISSUE THREAD

**Issue by rutillastoby** [rutillastoby/zoa#3]
1. Sería necesario que los usuarios notifiquen su **ubicación** a la base de datos de forma **más continua**, ya que actualmente se prolonga mucho en su actualización (500m aprox).

2. Las marcas dentro de la aplicación de administración de algunos **usuarios desaparecían del mapa** tras un tiempo de forma inesperada, se debe comprobar este comportamiento para tener siempre la ultima ubicación de cada usuario visible en el mapa.
Este comportamiento quizás pueda estar relacionado con el cierre de la aplicación por parte del usuario donde se establezca a null (0,0) su ubicación, en cuyo caso habría que suprimir este comportamiento para que no se elimine su marca del mapa de control.

**Comment by angelsalascalvo** [comment]
Se ha cambiado el sistema de envío de ubicación de los jugadores por completo, almacenando actualmente el historial de ubicaciones en base de datos con el fin de poder crear una trazada del recorrido seguido.
